# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(max_length=255)),
                ('Estado', models.CharField(max_length=255)),
                ('IDcliente', models.IntegerField()),
            ],
        ),
    ]
