# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:21
from __future__ import unicode_literals

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_auto_20170330_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='id_cliente',
            field=models.IntegerField(blank=True, null=True, verbose_name=clientes.models.Cliente),
        ),
    ]
