# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_auto_20170330_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='Estado',
            field=models.ManyToManyField(to='cotizaciones.Estados'),
        ),
    ]
