# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_cotizacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Estados',
        ),
    ]
