# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_auto_20170330_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='Estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.Estados'),
        ),
    ]
